layer.conf: update LAYERDEPENDS_signing-key
Fix yocto-check-layer failure:
ERROR: Nothing PROVIDES 'efitools-native' (but /layers/meta-secure-core/meta-signing-key/recipes-devtools/gen-sbkeys/gen-sbkeys.bb DEPENDS on or otherwise requires it). Close matches:
  libtool-native
  mtools-native
  net-tools-native
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'gen-sbkeys', 'efitools-native']

gen-sbkeys depends on efitools-native, efitools-native is under layer efi-secure-boot

Signed-off-by: Changqing Li <changqing.li@windriver.com>