meta-signing-key: Update LAYERDEPENDS
Add openembedded-layer to LAYERDEPENDS to fix the below errror.
  ERROR: Nothing PROVIDES 'nspr' (but /build/layers/meta-secure-core/meta-signing-key/recipes-devtools/pesign/pesign_git.bb DEPENDS on or otherwise requires it)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'pesign', 'nspr']

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>