shim: install shim.efi instead of boot.efi if MOK_SB=0
There is a do_rootfs error in secure-core-image when UEFI_SB = 1 and
MOK_SB = 0:
Error: Transaction test error:
  file /boot/efi/EFI/BOOT/bootx64.efi conflicts between attempted installs of seloader-0.4.6+git0+8b90f76a8d-r0.core2_64 and shim-15.8-r0.core2_64

When MOK_SB=0, SELoader will become the first stage loader and
SELoader.efi will be renamed to bootx64.efi. This will conflict with
bootx64.efi in shim.
To avoid this conflict, install shimx64.efi instead of bootx64.efi in
shim if MOK_SB=0

Fixes: #64

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>