meta-integrity: Add Upstream-Status field
Fixes:
  INFO: Traceback (most recent call last):
  File "/build/layers/oe-core/scripts/lib/checklayer/cases/common.py", line 87, in test_patches_upstream_status
    self.assertEqual(len(patches), 0 , \
  AssertionError: 1 != 0 : Found following patches with malformed or missing upstream status:
  /build/layers/meta-secure-core/meta-integrity/recipes-support/ima-evm-utils/ima-evm-utils/0001-Install-evmctl-to-sbindir-rather-than-bindir.patch

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>