grub-efi: add support for build without shim
In `meta-signing-key/classes/user-key-store.bbclass` file, there is already
an implementation of sb_sign() function with support for both scerarions:
- bootloader is verified by shim_cert.crt
- shim is not used, and DB.crt is used to verify bootloader directly

but when building with MOK_SB ?= "0", grub is being build as `grub(ia32/x64).efi`
and with shim_lock support enabled.

Disabling shim_lock for running secure boot without shim fixes the issue:

  error: ../../grub-core/kern/efi/sb.c:180:shim_lock protocol not found.

during boot.

Disabling renaming of grub efi into `grubx64.efi` leaves it, as it is in
EFI_BOOT_IMAGE variable, set in `yocto/openembedded-core/meta/conf/image-uefi.conf`,
as this will be our first efi boot file.

Signed-off-by: Piotr Łobacz <p.lobacz@welotec.com>