linux-yocto-efi-secure-boot.inc: fix missing prefuncs
There is a do_sign_bundled_kernel in kernel build when UEFI_SELOADER = 0 and
GRUB_SIGN_VERIFY = 1:
Error: Failed to sign error:
  file /boot/bzImage.initramfs fails to be signed within do_sign_bundled_kernel function

When do_sign_bundled_kernel is called there is no access to deployed keys within
boot_sign as gpg_path is empty, thus check_deploy_keys and check_boot_public_key
are being added into do_sign_bundled_kernel[prefuncs]

Fixes: #85

Signed-off-by: Piotr Łobacz <p.lobacz@welotec.com>