meta-efi-secure-boot: Add Upstream-Status field
Fixes:
  INFO: Traceback (most recent call last):
  File "/build/layers/oe-core/scripts/lib/checklayer/cases/common.py", line 87, in test_patches_upstream_status
    self.assertEqual(len(patches), 0 , \
AssertionError: 1 != 0 : Found following patches with malformed or missing upstream status:
  /build/layers/meta-secure-core/meta-efi-secure-boot/recipes-bsp/efitools/efitools/0015-fix-segfault-for-efitools-commands.patch

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>