meta-encrypted-storage: fix failure to find linux-yocto-luks.inc
linux-yocto-luks.inc is shared among linux-yocto, linux-yocto-rt and
linux-yocto-dev and cannot be found with ${BPN} in the latter two.

ERROR: ParseError at layers/meta-secure-core/meta-encrypted-storage/recipes-kernel/linux/linux-yocto-dev.bbappend:1:
Could not include required file linux-yocto-dev-luks.inc
ERROR: ParseError at layers/meta-secure-core/meta-encrypted-storage/recipes-kernel/linux/linux-yocto-rt_%.bbappend:1:
Could not include required file linux-yocto-rt-luks.inc

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>