grub: remove unused parameter from grub_efi_mok2_verify_file_buffer function
The parameter 'const char *path' in grub_efi_mok2_verify_file_buffer
function is useless. Remove it to avoid grub-efi build error with gcc14:

../../grub-2.12/grub-core/lib/efi/mok2verify.c:207:83: error: passing
argument 6 of 'mok2->verify_file_buffer' from incompatible pointer type [-Wincompatible-pointer-types]
  207 |   status = mok2->verify_file_buffer(mok2, data, data_size, sigdata, sigdata_size, path);
      |                                                                                   ^~~~
      |                                                                                   |
      |                                                                                   const char *
../../grub-2.12/grub-core/lib/efi/mok2verify.c:207:83: note: expected 'const grub_efi_char16_t *'
{aka 'const short unsigned int *'} but argument is of type 'const char *'

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>