grub-efi bbappend: fix grub error message
The cmdpath is a root partition name when secure-boot enabled.
search.file (hd0,gpt1)/EFI/BOOT/grub.cfg root would cause an error message:

      error: no such device: ((hd0,msdos1)/EFI/BOOT)/EFI/BOOT/grub.cfg.

Since root = (hd0,gpt1) is a default value, it needn't to set be via search.file, but
that might cause confusion for customers, so remove $cmdpath on non UEFI seloader mode.

Signed-off-by: Xiangyu Chen <xiangyu.chen@windriver.com>