meta-tpm2: Update LAYERDEPENDS
Add openembedded-layer and meta-python to LAYERDEPENDS to fix
the below error:
  ERROR: Nothing PROVIDES 'qrencode' (but /build/layers/meta-secure-core/meta-tpm2/recipes-tpm/tpm2-totp/tpm2-totp_0.3.0.bb DEPENDS on or otherwise requires it)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'tpm2-totp', 'qrencode']

  ERROR: Nothing PROVIDES 'python3-pkgconfig-native' (but /build/layers/meta-secure-core/meta-tpm2/recipes-tpm/tpm2-pytss/tpm2-pytss_2.2.1.bb DEPENDS on or otherwise requires it). Close matches:
    python3-cffi-native
    python3-iniconfig-native
    python3-scons-native
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'tpm2-pytss', 'python3-pkgconfig-native']

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>